cmake_minimum_required(VERSION 3.11)


add_subdirectory(sprint1/problems/sum/solution)
add_subdirectory(sprint1/problems/radio/solution)
add_subdirectory(sprint1/problems/seabattle/solution)
add_subdirectory(sprint1/problems/sync_server/solution)
add_subdirectory(sprint1/problems/restaurant_single_threaded/solution)
#add_subdirectory(sprint1/problems/restaurant_multi_threaded/solution)
add_subdirectory(sprint1/problems/cafeteria/solution)
add_subdirectory(sprint1/problems/async_server/solution)
#add_subdirectory(sprint1/problems/map_json/solution)
#add_subdirectory(sprint2/problems/static_content/solution)
add_subdirectory(sprint2/problems/logger/solution)
# add_subdirectory(sprint2/problems/server_logging/solution)
# add_subdirectory(sprint2/problems/join_game/solution)
# add_subdirectory(sprint2/problems/game_state/solution)
# add_subdirectory(sprint2/problems/move_players/solution)
# add_subdirectory(sprint2/problems/time_control/solution)
# add_subdirectory(sprint2/problems/command_line/solution)
# add_subdirectory(sprint3/problems/gen_objects/solution)
# add_subdirectory(sprint3/problems/static_lib/solution)
# add_subdirectory(sprint3/problems/gather-tests/solution)
# add_subdirectory(sprint3/problems/gather/solution)
# add_subdirectory(sprint3/problems/find_return/solution)
# add_subdirectory(sprint3/problems/scores/solution)
# add_subdirectory(sprint4/problems/state_serialization/solution)
# add_subdirectory(sprint4/problems/bookypedia-1/solution)
add_subdirectory(sprint4/problems/bookypedia-2/solution)
add_subdirectory(sprint4/problems/db_of_books/solution)
add_subdirectory(sprint4/problems/leave_game/solution)

